apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "citadel.fullname" . }}-api
  labels:
    {{- include "citadel.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "citadel.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "citadel.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: api
          image: {{ include "citadel.image" (dict "ctx" . "component" .Values.api) }}
          imagePullPolicy: {{ include "citadel.pullPolicy" (dict "ctx" . "component" .Values.api) }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "citadel.fullname" . }}-config
            - secretRef:
                name: {{ .Values.secret.existingSecret | default (printf "%s-secret" (include "citadel.fullname" .)) }}
          livenessProbe:
            {{- toYaml .Values.api.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.api.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
