apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: __FO_NAMESPACE__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.13.0
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch-service:9200"
            - name: SERVER_BASEPATH
              value: "/kibana"
            - name: SERVER_REWRITEBASEPATH
              value: "true"
            - name: XPACK_SECURITY_ENABLED
              value: "false"
          ports:
            - containerPort: 5601
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /kibana/api/status
              port: 5601
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: __FO_NAMESPACE__
spec:
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
