"""
Investigation report generator.

Pulls everything needed to deliver a case writeup:
  - Case metadata
  - Pinned events (curated evidence) — top of report
  - Flagged events (triage queue) — mid report
  - Analyst notes (Markdown WYSIWYG)
  - MITRE technique coverage
  - Watchlist hits (auto-eval)
  - Detection rule matches

Renders Markdown by default. PDF generation is optional (requires WeasyPrint
or similar — falls back to plain text if unavailable).
"""

from __future__ import annotations

import json
import logging
from datetime import UTC, datetime

import redis_keys as rk
from auth.dependencies import require_case_access
from fastapi import APIRouter, Depends
from fastapi.responses import Response
from services.elasticsearch import _request as es_req

from config import get_redis

logger = logging.getLogger(__name__)
router = APIRouter(tags=["reports"])


def _ts(s: str) -> str:
    """Pretty-print an ISO timestamp; passthrough if unparseable."""
    if not s:
        return ""
    try:
        return datetime.fromisoformat(s.replace("Z", "+00:00")).strftime("%Y-%m-%d %H:%M:%S UTC")
    except Exception:
        return s


# ── Report template ───────────────────────────────────────────────────────────
# Org-wide customization of the generated report: branding header/footer,
# title prefix, and per-section toggles. Stored in fo:report_template.

_REPORT_TEMPLATE_KEY = "fo:report_template"

_TEMPLATE_DEFAULTS = {
    "title_prefix": "Investigation report",
    "header_md": "",  # org branding block, rendered right under the title
    "footer_md": "_Generated by Citadel_",
    "max_flagged": 50,
    "sections": {  # toggle any section off org-wide
        "exec_summary": True,
        "ai_report": True,
        "pinned": True,
        "flagged": True,
        "mitre": True,
        "detections": True,
        "watchlist": True,
        "notes": True,
    },
}


def _load_template() -> dict:
    """Stored template merged over defaults — missing keys fall back."""
    tpl = dict(_TEMPLATE_DEFAULTS)
    tpl["sections"] = dict(_TEMPLATE_DEFAULTS["sections"])
    try:
        raw = get_redis().get(_REPORT_TEMPLATE_KEY)
        if raw:
            stored = json.loads(raw)
            for k in ("title_prefix", "header_md", "footer_md"):
                if isinstance(stored.get(k), str):
                    tpl[k] = stored[k]
            if isinstance(stored.get("max_flagged"), int) and stored["max_flagged"] > 0:
                tpl["max_flagged"] = min(stored["max_flagged"], 500)
            for k, v in (stored.get("sections") or {}).items():
                if k in tpl["sections"]:
                    tpl["sections"][k] = bool(v)
    except Exception:
        pass
    return tpl


def _fetch_pinned(case_id: str, size: int = 200) -> list[dict]:
    body = {
        "query": {"term": {"is_pinned": True}},
        "size": size,
        "sort": [{"timestamp": {"order": "asc", "unmapped_type": "keyword", "missing": "_last"}}],
    }
    try:
        r = es_req("POST", f"/fo-case-{case_id}-*/_search", body)
        return [h["_source"] for h in r.get("hits", {}).get("hits", [])]
    except Exception:
        return []


def _fetch_flagged(case_id: str, size: int = 200) -> list[dict]:
    body = {
        "query": {"term": {"is_flagged": True}},
        "size": size,
        "sort": [{"timestamp": {"order": "asc", "unmapped_type": "keyword", "missing": "_last"}}],
    }
    try:
        r = es_req("POST", f"/fo-case-{case_id}-*/_search", body)
        return [h["_source"] for h in r.get("hits", {}).get("hits", [])]
    except Exception:
        return []


def _fetch_mitre(case_id: str) -> dict:
    # Field shapes mirror search.py mitre_coverage: live data uses mitre.id
    # (text → aggregate on .keyword) and mitre.technique (.keyword), with
    # mitre.tactic mapped as keyword directly.
    body = {
        "size": 0,
        "query": {"exists": {"field": "mitre.id"}},
        "aggs": {
            "by_technique": {
                "terms": {"field": "mitre.id.keyword", "size": 100},
                "aggs": {
                    "top_name": {"terms": {"field": "mitre.technique.keyword", "size": 1}},
                    "top_tactic": {"terms": {"field": "mitre.tactic", "size": 1}},
                },
            },
        },
    }
    try:
        res = es_req("POST", f"/fo-case-{case_id}-*/_search", body)
    except Exception:
        return {"techniques": []}
    techniques = []
    for b in res.get("aggregations", {}).get("by_technique", {}).get("buckets", []):
        names = b.get("top_name", {}).get("buckets", [])
        tactics = b.get("top_tactic", {}).get("buckets", [])
        techniques.append(
            {
                "id": b["key"],
                "name": names[0]["key"] if names else b["key"],
                "tactic": tactics[0]["key"] if tactics else "",
                "count": b["doc_count"],
            }
        )
    return {"techniques": techniques}


def _fetch_watchlist_run(case_id: str) -> dict:
    raw = get_redis().get(f"fo:watchlist_runs:{case_id}")
    if not raw:
        return {}
    try:
        return json.loads(raw.decode() if isinstance(raw, bytes) else raw)
    except Exception:
        return {}


def _fetch_detection_run(case_id: str) -> dict:
    raw = get_redis().get(rk.case_alert_run(case_id))
    if not raw:
        return {}
    try:
        return json.loads(raw.decode() if isinstance(raw, bytes) else raw)
    except Exception:
        return {}


def _fetch_notes(case_id: str) -> str:
    raw = get_redis().get(f"case:{case_id}:notes")
    if not raw:
        return ""
    s = raw.decode() if isinstance(raw, bytes) else raw
    # Strip surrounding JSON if stored that way
    try:
        return json.loads(s).get("body", s) if s.startswith("{") else s
    except Exception:
        return s


def _fetch_ai_report(case_id: str) -> dict | None:
    """Pull the AI Investigation Report (auto-written by the Autopilot agent
    or generated manually). Format: { content, generated_at, model_used, ... }"""
    raw = get_redis().get(f"case:{case_id}:ai:report")
    if not raw:
        return None
    s = raw.decode() if isinstance(raw, bytes) else raw
    try:
        return json.loads(s)
    except Exception:
        return None


def _event_line(ev: dict) -> str:
    """Single-line event summary for the report."""
    ts = _ts(ev.get("timestamp", ""))
    atype = ev.get("artifact_type", "?")
    host = (ev.get("host") or {}).get("hostname", "")
    user = (ev.get("user") or {}).get("name", "")
    msg = (ev.get("message") or "").strip().splitlines()[0][:240]
    bits = [f"`{ts}`" if ts else "", f"**{atype}**"]
    if host:
        bits.append(f"@ `{host}`")
    if user:
        bits.append(f"user `{user}`")
    bits.append(f"— {msg}" if msg else "")
    return " ".join(b for b in bits if b)


def _render_markdown(
    case: dict,
    pinned: list,
    flagged: list,
    mitre: dict,
    wl: dict,
    det: dict,
    notes: str,
    ai_report: dict | None = None,
    tpl: dict | None = None,
) -> str:
    tpl = tpl or _load_template()
    sections = tpl.get("sections") or {}
    out: list[str] = []
    name = case.get("name", case.get("case_id", "Case"))
    out.append(f"# {tpl.get('title_prefix') or 'Investigation report'} — {name}")
    out.append("")
    if (tpl.get("header_md") or "").strip():
        out.append(tpl["header_md"].strip())
        out.append("")
    out.append(f"_Generated {_ts(datetime.now(UTC).isoformat())}_")
    if case.get("company"):
        out.append(f"_Company: {case['company']}_")
    out.append("")

    # Executive summary derived from the data we have
    if sections.get("exec_summary", True):
        out.append("## Executive summary")
        out.append("")
        out.append(f"- **{len(pinned)} pinned event(s)** curated as key evidence.")
        out.append(f"- **{len(flagged)} flagged event(s)** under analyst review.")
        out.append(f"- **{len(mitre.get('techniques', []))} MITRE ATT&CK techniques** evidenced.")
        if wl and wl.get("hits"):
            out.append(f"- **{len(wl['hits'])} IOC watchlist hit(s)** in the latest sweep.")
        if det and det.get("matches"):
            out.append(f"- **{len(det['matches'])} detection rule(s)** fired.")
        out.append("")

    # ── AI Autopilot investigation (when one ran on this case) ──────────────
    # Folded into the flat report so the non-AI deliverable still surfaces
    # the agent's findings. The block is the LLM-polished markdown already,
    # so we just inline it under its own H2.
    if sections.get("ai_report", True) and ai_report and (ai_report.get("content") or "").strip():
        out.append("---")
        out.append("")
        out.append("## AI Autopilot investigation")
        out.append("")
        meta_bits = []
        if ai_report.get("generated_at"):
            meta_bits.append(f"_generated {_ts(ai_report['generated_at'])}_")
        if ai_report.get("model_used"):
            meta_bits.append(f"_{ai_report['model_used']}_")
        if ai_report.get("source"):
            meta_bits.append(f"_source: {ai_report['source']}_")
        if meta_bits:
            out.append(" · ".join(meta_bits))
            out.append("")
        # Strip any top-level "# " heading from the AI content so the section
        # nesting stays tidy (the LLM emits "# Executive Summary" which would
        # otherwise outrank our case title).
        ai_content = (ai_report["content"] or "").strip()
        ai_content = "\n".join(
            ("##" + ln[1:]) if ln.startswith("# ") else ln for ln in ai_content.splitlines()
        )
        out.append(ai_content)
        out.append("")

    # Pinned events (the curated narrative)
    if sections.get("pinned", True) and pinned:
        out.append("## Key evidence (pinned events)")
        out.append("")
        for ev in pinned:
            out.append(f"- {_event_line(ev)}")
            if ev.get("pin_note"):
                out.append(f"  > _{ev['pin_note']}_")
        out.append("")

    # Flagged
    max_flagged = int(tpl.get("max_flagged") or 50)
    if sections.get("flagged", True) and flagged:
        out.append("## Flagged events")
        out.append("")
        for ev in flagged[:max_flagged]:
            out.append(f"- {_event_line(ev)}")
        if len(flagged) > max_flagged:
            out.append(f"_…and {len(flagged) - max_flagged} more._")
        out.append("")

    # MITRE
    techs = mitre.get("techniques", []) if sections.get("mitre", True) else []
    if techs:
        out.append("## MITRE ATT&CK coverage")
        out.append("")
        by_tactic: dict[str, list] = {}
        for t in techs:
            by_tactic.setdefault(t["tactic"] or "Unknown", []).append(t)
        for tactic, items in sorted(by_tactic.items()):
            out.append(f"### {tactic}")
            for t in sorted(items, key=lambda x: -x["count"]):
                out.append(f"- `{t['id']}` {t['name']} — {t['count']} event(s)")
            out.append("")

    # Detection rules
    if sections.get("detections", True) and det and det.get("matches"):
        out.append("## Detection rules that fired")
        out.append("")
        out.append(f"_Last run: {_ts(det.get('ran_at', ''))}_")
        for m in det["matches"]:
            rule = m.get("rule") or {}
            out.append(f"- **{rule.get('name', '?')}** ({m.get('match_count', 0)} match(es))")
            if rule.get("description"):
                out.append(f"  > {rule['description']}")
        out.append("")

    # Watchlist
    if sections.get("watchlist", True) and wl and wl.get("hits"):
        out.append("## IOC watchlist hits")
        out.append("")
        out.append(f"_Auto-sweep: {_ts(wl.get('ran_at', ''))}_")
        for h in wl["hits"]:
            out.append(f"- **{h.get('label')}** (`{h.get('kind')}`) — {h.get('hits')} match(es)")
            out.append(f"  - Query: `{h.get('query')}`")
        out.append("")

    # Notes
    if sections.get("notes", True) and notes:
        out.append("## Analyst notes")
        out.append("")
        out.append(notes)
        out.append("")

    out.append("---")
    if (tpl.get("footer_md") or "").strip():
        out.append(tpl["footer_md"].strip())
    return "\n".join(out)


@router.get("/cases/{case_id}/report.md")
def report_markdown(case_id: str, case: dict = Depends(require_case_access)):
    md = _render_markdown(
        case=case,
        pinned=_fetch_pinned(case_id),
        flagged=_fetch_flagged(case_id),
        mitre=_fetch_mitre(case_id),
        wl=_fetch_watchlist_run(case_id),
        det=_fetch_detection_run(case_id),
        notes=_fetch_notes(case_id),
        ai_report=_fetch_ai_report(case_id),
    )
    safe_name = (case.get("name") or case_id).replace("/", "_")[:80]
    return Response(
        content=md,
        media_type="text/markdown; charset=utf-8",
        headers={"Content-Disposition": f'attachment; filename="{safe_name}-report.md"'},
    )


@router.get("/cases/{case_id}/report.html")
def report_html(case_id: str, case: dict = Depends(require_case_access)):
    """Self-contained HTML render — printable, screenshots cleanly."""
    md = _render_markdown(
        case=case,
        pinned=_fetch_pinned(case_id),
        flagged=_fetch_flagged(case_id),
        mitre=_fetch_mitre(case_id),
        wl=_fetch_watchlist_run(case_id),
        det=_fetch_detection_run(case_id),
        notes=_fetch_notes(case_id),
        ai_report=_fetch_ai_report(case_id),
    )
    # Minimal MD → HTML — server-side; client could also handle this.
    html_body = _md_to_html_minimal(md)
    safe_name = (case.get("name") or case_id).replace("/", "_")[:80]
    page = f"""<!doctype html>
<html><head><meta charset="utf-8"/>
<title>{safe_name} — Citadel report</title>
<style>
  body {{ font: 14px/1.55 -apple-system, BlinkMacSystemFont, 'Segoe UI', Inter, sans-serif;
          color: #0F172A; max-width: 880px; margin: 2em auto; padding: 0 1em; }}
  h1, h2, h3 {{ color: #111827; letter-spacing: -0.015em; }}
  h1 {{ font-size: 1.8em; border-bottom: 1px solid #E5E7EB; padding-bottom: 0.4em; }}
  h2 {{ font-size: 1.3em; margin-top: 2em; }}
  h3 {{ font-size: 1.05em; color: #4B5563; }}
  code {{ background: #F3F4F6; padding: 0.1em 0.35em; border-radius: 3px;
          font-family: 'JetBrains Mono', Consolas, monospace; font-size: 0.92em; }}
  blockquote {{ border-left: 3px solid #6366F1; margin: 0.5em 0; padding: 0.2em 1em;
                color: #4B5563; background: #F9FAFB; }}
  ul {{ padding-left: 1.6em; }}
  li {{ margin-bottom: 0.2em; }}
  hr {{ border: none; border-top: 1px solid #E5E7EB; margin: 2em 0; }}
  @media print {{ body {{ max-width: 100%; }} }}
</style>
</head><body>
{html_body}
</body></html>"""
    return Response(
        content=page,
        media_type="text/html; charset=utf-8",
        headers={"Content-Disposition": f'attachment; filename="{safe_name}-report.html"'},
    )


def _md_to_html_minimal(md: str) -> str:
    """Very small Markdown → HTML — enough for our report shape (headings,
    lists, blockquotes, inline code, bold). No external dep."""
    lines = md.splitlines()
    out: list[str] = []
    in_list = False
    for raw in lines:
        line = raw.rstrip()
        if not line:
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append("")
            continue
        if line.startswith("# "):
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append(f"<h1>{_inline(line[2:])}</h1>")
            continue
        if line.startswith("## "):
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append(f"<h2>{_inline(line[3:])}</h2>")
            continue
        if line.startswith("### "):
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append(f"<h3>{_inline(line[4:])}</h3>")
            continue
        if line == "---":
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append("<hr/>")
            continue
        if line.startswith("- ") or line.startswith("  > "):
            if line.startswith("  > "):
                out.append(f"<blockquote>{_inline(line[4:])}</blockquote>")
                continue
            if not in_list:
                out.append("<ul>")
                in_list = True
            out.append(f"<li>{_inline(line[2:])}</li>")
            continue
        if in_list:
            out.append("</ul>")
            in_list = False
        out.append(f"<p>{_inline(line)}</p>")
    if in_list:
        out.append("</ul>")
    return "\n".join(out)


def _inline(s: str) -> str:
    import re as _re

    # escape, then re-apply allowed inline marks
    s = s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    s = _re.sub(r"`([^`]+)`", r"<code>\1</code>", s)
    s = _re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", s)
    s = _re.sub(r"_([^_]+)_", r"<em>\1</em>", s)
    return s


# ── Report template admin endpoints ──────────────────────────────────────────

from auth.dependencies import require_admin  # noqa: E402
from pydantic import BaseModel  # noqa: E402


class ReportTemplateIn(BaseModel):
    title_prefix: str = "Investigation report"
    header_md: str = ""
    footer_md: str = "_Generated by Citadel_"
    max_flagged: int = 50
    sections: dict = {}


@router.get("/admin/report-template", dependencies=[Depends(require_admin)])
def get_report_template():
    return _load_template()


@router.put("/admin/report-template", dependencies=[Depends(require_admin)])
def set_report_template(body: ReportTemplateIn):
    sections = dict(_TEMPLATE_DEFAULTS["sections"])
    for k, v in (body.sections or {}).items():
        if k in sections:
            sections[k] = bool(v)
    tpl = {
        "title_prefix": (body.title_prefix or "Investigation report")[:120],
        "header_md": (body.header_md or "")[:4000],
        "footer_md": (body.footer_md or "")[:1000],
        "max_flagged": min(max(1, body.max_flagged), 500),
        "sections": sections,
    }
    get_redis().set(_REPORT_TEMPLATE_KEY, json.dumps(tpl))
    return tpl


@router.delete("/admin/report-template", dependencies=[Depends(require_admin)])
def reset_report_template():
    get_redis().delete(_REPORT_TEMPLATE_KEY)
    return _load_template()
