"""
LicenseClient — validates a signed JWT license key.

Resolution flow:
  1. Read CITADEL_LICENSE_KEY from env.
  2. Decode + verify with CITADEL_LICENSE_SIGNING_KEY (HS256).
  3. If valid (signature, not expired) → use the embedded plan + features.
  4. If absent, invalid, or expired → fall back to the community license.

There is only ONE deployment mode now. No env switches to unlock features;
the only way to upgrade beyond community is a signed key generated by
`scripts/generate-license.py`.

Time-limited keys: the JWT's `exp` claim is honoured. A 14-day trial enterprise
key would simply expire after 14 days and the system reverts to community —
without any operator action.
"""

from __future__ import annotations

import json
import logging
import os
import tempfile
import threading
import time
from pathlib import Path

import jwt

from .models import PLAN_FEATURES, PLAN_LABELS, LicenseInfo, community_license

logger = logging.getLogger(__name__)

CACHE_TTL_SECONDS = 600  # 10 min — keeps expiry checks fresh without thrashing JWT decode

# Public default secret used to sign the bundled community license. Operators
# rotate to their own secret in production. Generators MUST use the matching
# secret — there's no escape hatch.
DEFAULT_SIGNING_KEY = "citadel-default-public-signing-key-DO-NOT-USE-IN-PRODUCTION"

# Persisted-from-UI overrides. Sits on a writable PVC (uploads-pvc) so it
# survives pod restarts. Takes precedence over env vars when present.
LICENSE_OVERRIDE_FILE = Path(
    os.getenv("CITADEL_LICENSE_FILE", "/app/uploads/.citadel-license.json")
)


class LicenseClient:
    def __init__(self) -> None:
        self._env_key: str = (os.getenv("CITADEL_LICENSE_KEY") or "").strip()
        self._env_signing_key: str = (os.getenv("CITADEL_LICENSE_SIGNING_KEY") or "").strip()
        self._key: str = self._env_key
        self._signing_key: str = self._env_signing_key or DEFAULT_SIGNING_KEY
        self._source: str = "env" if self._env_key else "default"
        self._lock = threading.RLock()
        self._cache: LicenseInfo | None = None
        self._cache_until: float = 0.0
        self._load_overrides_if_present()

    def _load_overrides_if_present(self) -> None:
        """File override > env. Silently ignore unreadable/malformed file."""
        try:
            if not LICENSE_OVERRIDE_FILE.is_file():
                return
            data = json.loads(LICENSE_OVERRIDE_FILE.read_text("utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            logger.warning("License override file unreadable: %s", exc)
            return
        key = (data.get("key") or "").strip()
        sk = (data.get("signing_key") or "").strip()
        if not key:
            return
        self._key = key
        if sk:
            self._signing_key = sk
        self._source = "file"

    def set_license(self, key: str, signing_key: str | None = None) -> LicenseInfo:
        """Install a license at runtime + persist for restart survival.

        Validates the JWT against the supplied (or current) signing key before
        accepting. Raises on validation failure; the on-disk file is only
        written after a successful decode."""
        key = (key or "").strip()
        if not key:
            raise ValueError("license key is required")
        candidate_signing = (signing_key or "").strip() or self._signing_key
        # Verify before persisting — catches typos and signature mismatch up-front.
        jwt.decode(
            key,
            candidate_signing,
            algorithms=["HS256"],
            options={"verify_exp": True, "verify_signature": True},
        )
        with self._lock:
            payload = {"key": key}
            if signing_key:
                payload["signing_key"] = candidate_signing
            try:
                LICENSE_OVERRIDE_FILE.parent.mkdir(parents=True, exist_ok=True)
                # Atomic write: stage in a temp file in the same directory and
                # rename it over the target. Rename only needs write on the
                # *directory*, so this still succeeds when an existing license
                # file is owned by another user (e.g. a root-owned file left by a
                # pre-hardening pod that the non-root pod can no longer truncate),
                # and it never leaves a half-written license on crash.
                fd, tmp = tempfile.mkstemp(
                    dir=str(LICENSE_OVERRIDE_FILE.parent),
                    prefix=".citadel-license.",
                    suffix=".tmp",
                )
                try:
                    with os.fdopen(fd, "w", encoding="utf-8") as fh:
                        fh.write(json.dumps(payload))
                    os.chmod(tmp, 0o600)
                    os.replace(tmp, LICENSE_OVERRIDE_FILE)
                except OSError:
                    try:
                        os.unlink(tmp)
                    except OSError:
                        pass
                    raise
            except OSError as exc:
                raise RuntimeError(f"could not persist license file: {exc}") from exc
            self._key = key
            self._signing_key = candidate_signing
            self._source = "file"
            self._cache = None
            self._cache_until = 0.0
        return self.get()

    def clear_license(self) -> LicenseInfo:
        """Remove persisted override + revert to env (or community)."""
        with self._lock:
            try:
                LICENSE_OVERRIDE_FILE.unlink(missing_ok=True)
            except OSError as exc:
                logger.warning("Could not remove license override file: %s", exc)
            self._key = self._env_key
            self._signing_key = self._env_signing_key or DEFAULT_SIGNING_KEY
            self._source = "env" if self._env_key else "default"
            self._cache = None
            self._cache_until = 0.0
        return self.get()

    def get(self) -> LicenseInfo:
        with self._lock:
            now = time.monotonic()
            if self._cache is not None and now < self._cache_until:
                return self._cache
            info = self._resolve()
            self._cache = info
            self._cache_until = now + CACHE_TTL_SECONDS
            return info

    def invalidate(self) -> None:
        with self._lock:
            self._cache = None
            self._cache_until = 0.0

    def _resolve(self) -> LicenseInfo:
        if not self._key:
            return community_license("No license key configured — running on Community.")
        try:
            payload = jwt.decode(
                self._key,
                self._signing_key,
                algorithms=["HS256"],
                options={"verify_exp": True, "verify_signature": True},
            )
        except jwt.ExpiredSignatureError:
            logger.warning("License key has expired — falling back to Community.")
            return community_license("License expired — running on Community.")
        except jwt.InvalidSignatureError:
            logger.error(
                "License key signature is invalid (wrong CITADEL_LICENSE_SIGNING_KEY?) — falling back to Community."
            )
            return community_license("Invalid license signature — running on Community.")
        except Exception as exc:
            logger.error("License key could not be decoded: %s — falling back to Community.", exc)
            return community_license(f"License decode failed: {exc}")

        plan = (payload.get("plan") or "community").strip().lower()
        if plan not in PLAN_FEATURES:
            logger.warning(
                "License key references unknown plan %r — falling back to Community.", plan
            )
            return community_license(f"Unknown plan {plan!r} — running on Community.")

        valid_until = payload.get("exp")
        if isinstance(valid_until, (int, float)):
            valid_until = time.strftime("%Y-%m-%d", time.gmtime(valid_until))

        # Allow per-key feature overrides (e.g. trial enterprise with only ai_assist enabled).
        features = dict(PLAN_FEATURES[plan])
        if isinstance(payload.get("features"), dict):
            features.update(payload["features"])

        return LicenseInfo(
            valid=True,
            plan=plan,
            org_name=payload.get("org_name", "Licensed organization"),
            seats=int(payload.get("seats", 0)) or 1,
            valid_until=valid_until,
            features=features,
            message=payload.get("message", f"{PLAN_LABELS.get(plan, plan)} plan active"),
        )

    @property
    def info(self) -> dict:
        """Snapshot for /license/info — no secrets."""
        info = self.get()
        return {
            "valid": info.valid,
            "plan": info.plan,
            "plan_label": info.plan_label,
            "org_name": info.org_name,
            "seats": info.seats,
            "valid_until": info.valid_until,
            "features": info.features,
            "upgrade_to": info.upgrade_to,
            "message": info.message,
            "key_present": bool(self._key),
            "source": self._source,  # 'file' | 'env' | 'default'
            "can_install": True,  # UI can call POST /license/install
        }


_client = LicenseClient()


def get_license() -> LicenseInfo:
    """Module-level shortcut used throughout the codebase."""
    return _client.get()


def invalidate_license_cache() -> None:
    _client.invalidate()
